---
# PX Storage Classes
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-mssql-db
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  io_profile: "random"
  priority_io: "high"
allowVolumeExpansion: true
---
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-mssql-logs
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  io_profile: "random"
  priority_io: "high"
allowVolumeExpansion: true
---
# Loadbalancer Service
apiVersion: v1
kind: Service
metadata:
  name:  px-mssql
spec:
  selector:
    app:  mssql
  type:  LoadBalancer
  ports:
  - name:  mssql
    port:  1433
    targetPort: 1433
---
# MSSQL StatefulSet with PX Volumes
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mssql
spec:
  serviceName: mssql-tpc
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      schedulerName: stork
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "P0rtw0rx!"
          - name: MSSQL_DATA_DIR
            value: /var/opt/mssql/data
          - name: MSSQL_LOG_DIR
            value: /var/opt/mssql/logs
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssql-data
          mountPath: /var/opt/mssql/data
        - name: mssql-logs
          mountPath: /var/opt/mssql/logs
      volumes:
      - name: mssql-data
        persistentVolumeClaim:
          claimName: px-mssql-sc
      - name: mssql-logs
        persistentVolumeClaim:
          claimName: px-mssql-logs-sc
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      storageClassName: px-mssql-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: mssql-logs
    spec:
      storageClassName: px-mssql-logs
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi