---
# PX Storage Classes
kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  name: px-mssql-db
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "1"
  io_profile: "random"
  priority_io: "high"
allowVolumeExpansion: true
---
# Loadbalancer Service
apiVersion: v1
kind: Service
metadata:
  name:  px-mssql
spec:
  selector:
    app:  mssql
  type:  LoadBalancer
  ports:
  - name:  mssql
    port:  1433
    targetPort: 1433
---
# MSQL Config_Map
kind: ConfigMap
apiVersion: v1
metadata:
  name: mssql-config
data:
  mssql.conf: |
    [EULA]
    accepteula = Y
    accepteulaml = Y
    [coredump]
    captureminiandfull = true
    coredumptype = full
    [hadr]
    hadrenabled = 1
    [language]
    lcid = 1033
    [filelocation]
    defaultdatadir = /var/opt/mssql/userdata
    defaultlogdir = /var/opt/mssql/userlog

---
# MSSQL StatefulSet with PX Volumes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      schedulerName: stork
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: mssql
        command:
          - /bin/bash
          - -c
          - cp /var/opt/config/mssql.conf /var/opt/mssql/mssql.conf && /opt/mssql/bin/sqlservr
        image: mcr.microsoft.com/mssql/server:2019-latest
        imagePullPolicy: ifNotPresent
        resources:
          requests:
            cpu: 2
            memory: 4Gi
        env:
          - name: ACCEPT_EULA
            value: "Y"
          - name: SA_PASSWORD
            value: "P0rtw0rx!"
          - name: MSSQL_AGENT_ENABLED
            value: "true"
          - name: MSSQL_PID
            value: "Developer"
        ports:
        - containerPort: 1433
        volumeMounts:
        - name: mssqluserdb
          mountPath: /var/opt/mssql/userdata
        - name: mssqllog
          mountPath: /var/opt/mssql/userlogs
        - name: mssqldb
          mountPath: /var/opt/mssql
        - name: mssqltemp
          mountPath: /var/opt/mssql/tempdb
        - name: mssql-config-volume
          mountPath: /var/opt/config
      volumes:
      - name: mssqldb
        persistentVolumeClaim:
          claimName: mssql-data
      - name: mssqluserdb
        persistentVolumeClaim:
          claimName: mssql-userdb
      - name: mssqllog
        persistentVolumeClaim:
          claimName: mssql-log
      - name: mssqltemp
        persistentVolumeClaim:
          claimName: mssql-temp
      - name: mssql-config-volume
        configMap:
          name: mssql-config
  volumeClaimTemplates:
  - metadata:
      name: mssql-data
    spec:
      storageClassName: px-mssql-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
  - metadata:
      name: mssql-userdb
    spec:
      storageClassName: px-mssql-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  - metadata:
      name: mssql-log
    spec:
      storageClassName: px-mssql-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: mssql-temp
    spec:
      storageClassName: px-mssql-db
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
---
